# Generated by Django 3.0.3 on 2020-08-24 18:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0002_league'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='League',
            new_name='Team',
        ),
    ]
